### PR TITLE
error corrections second pass

### PR DESCRIPTION
**Pull request by Vachenzo**

### CODE REVIEW

**Comment by insolor** [comment]
Please revert back from JS function names to Python ones.

**Comment by Vachenzo** [comment]
I've updated based on your recommendations, insolor. I copied over the wrong text for this file from my editor.

**Comment by insolor** [comment]
Just in case: I'm not a member of the CheckIO team, I just made a pull request for this file with a small fix and then see your pull request. The changes you propose IMO are great, but I noticed some mistakes and wanted to help.

Back to your pull request: pay attention to the `when_message` description, the original of the description is different then description of it's JS sibling, eg. there is no 'promises' in Python.

**Comment by Vachenzo** [comment]
That's fine. I'm actually a consultant and deal with editing the English content where I can. Since I don't typically work with these languages other than working with what Alex and the dev team give me, I mistook the differences between Py and JS. Thanks for catching it though, that would have been confusing.

**Comment by insolor** [comment]
One more correction: I think in the last sentence must be specified that `message` and `from_id` are _keys_ of the dict passed to the callback function. Something like "The `callback` function gets one argument as a dict with `message` and `from_id` keys." should be fine.

**Comment by Vachenzo** [comment]
Fixed. Thanks.

**Comment by oduvan** [comment]
@insolor Thank you

**Pull request merged**
